export const slides = [
  {
    image: "/hero-1.jpeg",
    caption: "Slide 1",
    text: "Find creative spaces in",
    highlight: "Lagos, Nigeria",
  },
  {
    image: "/hero-2.jpeg",
    caption: "Slide 2",
    text: "Discover curated spaces for",
    highlight: "Memorable Events",
  },
  {
    image: "/hero-3.jpeg",
    caption: "Slide 3",
    text: "Browse and scout",
    highlight: "200+ locations",
    afterText: "with real reviews",
  },
  {
    image: "/hero-4.jpeg",
    caption: "Slide 4",
    text: "Find creative spaces in",
    highlight: "Lagos, Nigeria",
  },
];

export const explore = [
  {
    image: "/ikoyi-link-bridge.jpeg",
    name: "Ikoyi",
    locationNumber: 7,
  },
  {
    image: "/yaba.jpeg",
    name: "Yaba",
    locationNumber: 5,
  },
  {
    image: "/ikeja.png",
    name: "Ikeja",
    locationNumber: 10,
  },
  {
    image: "/lekki-bridge.jpeg",
    name: "Lekki",
    locationNumber: 25,
  },
];

export const spaces = [
  {
    image: "/party.jpeg",
    name: "Party",
    spaceNumber: 10,
  },
  {
    image: "/content.jpeg",
    name: "Content",
    spaceNumber: 5,
  },
  {
    image: "/podcast.jpeg",
    name: "Podcasts",
    spaceNumber: 10,
  },
  {
    image: "/meetings.jpeg",
    name: "Meetings",
    spaceNumber: 25,
  },
  {
    image: "/popup.png",
    name: "Popup",
    spaceNumber: 25,
  },
];

export const submenuItems: Record<string, string[]> = {
    Locations: [
      "Yaba",
      "Lekki",
      "Ebute Metta",
      "Ikorodu",
      "Ikoyi",
      "Victoria Island",
    ],
    Activities: [
      "Photoshoot",
      "Videoshoot",
      "Party",
      "Dinner",
      "Large Gathering",
      "Training",
      "See All",
    ],
    "Space Types": [
      "Content House",
      "Photo Studio",
      "Podcast Room",
      "Party Room",
    ],
    Amenities: [
      "Free WiFi",
      "Lightening",
      "Abstract Props",
      "Wheelchair Accessible",
      "Graphic Walls",
    ],
  };

export const listings = [
  {
    images: ["/listing-1.jpeg", "/listing-2.jpeg", "/listing-3.jpeg", "/listing-4.jpeg"],
    name: "All Exclusive Shanty studios",
    location: "Ikeja, Lagos",
    ratings: "5.0",
    reviews: 10,
    price: "30,000",
    people: 10,
    instant: true,
  },
  {
    images: ["/listing-2.jpeg", "/listing-1.jpeg", "/listing-3.jpeg", "/listing-4.jpeg"],
    name: "All Exclusive Shanty studios",
    location: "Ikeja, Lagos",
    ratings: "4.9",
    reviews: 10,
    price: "30,000",
    people: 10,
    instant: false,
  },
  {
    images: ["/listing-3.jpeg", "/listing-2.jpeg", "/listing-1.jpeg", "/listing-4.jpeg"],
    name: "All Exclusive Shanty studios",
    location: "Ikeja, Lagos",
    ratings: "4.6",
    reviews: 10,
    price: "30,000",
    people: 10,
    instant: false,
  },
  {
    images: ["/listing-4.jpeg", "/listing-2.jpeg", "/listing-1.jpeg", "/listing-1.jpeg"],
    name: "All Exclusive Shanty studios",
    location: "Ikeja, Lagos",
    ratings: "4.5",
    reviews: 10,
    price: "30,000",
    people: 10,
    instant: true,
  },
  {
    images: ["/listing-1.jpeg", "/listing-2.jpeg", "/listing-3.jpeg", "/listing-4.jpeg"],
    name: "All Exclusive Shanty studios",
    location: "Ikeja, Lagos",
    ratings: "5.0",
    reviews: 10,
    price: "30,000",
    people: 10,
    instant: true,
  },
  {
    images: ["/listing-2.jpeg", "/listing-1.jpeg", "/listing-3.jpeg", "/listing-4.jpeg"],
    name: "All Exclusive Shanty studios",
    location: "Ikeja, Lagos",
    ratings: "4.9",
    reviews: 10,
    price: "30,000",
    people: 10,
    instant: false,
  },
  {
    images: ["/listing-3.jpeg", "/listing-2.jpeg", "/listing-1.jpeg", "/listing-4.jpeg"],
    name: "All Exclusive Shanty studios",
    location: "Ikeja, Lagos",
    ratings: "4.6",
    reviews: 10,
    price: "30,000",
    people: 10,
    instant: false,
  },
  {
    images: ["/listing-4.jpeg", "/listing-2.jpeg", "/listing-1.jpeg", "/listing-1.jpeg"],
    name: "All Exclusive Shanty studios",
    location: "Ikeja, Lagos",
    ratings: "4.5",
    reviews: 10,
    price: "30,000",
    people: 10,
    instant: true,
  },
  {
    images: ["/listing-1.jpeg", "/listing-2.jpeg", "/listing-3.jpeg", "/listing-4.jpeg"],
    name: "All Exclusive Shanty studios",
    location: "Ikeja, Lagos",
    ratings: "5.0",
    reviews: 10,
    price: "30,000",
    people: 10,
    instant: true,
  },
  {
    images: ["/listing-2.jpeg", "/listing-1.jpeg", "/listing-3.jpeg", "/listing-4.jpeg"],
    name: "All Exclusive Shanty studios",
    location: "Ikeja, Lagos",
    ratings: "4.9",
    reviews: 10,
    price: "30,000",
    people: 10,
    instant: false,
  },
  {
    images: ["/listing-3.jpeg", "/listing-2.jpeg", "/listing-1.jpeg", "/listing-4.jpeg"],
    name: "All Exclusive Shanty studios",
    location: "Ikeja, Lagos",
    ratings: "4.6",
    reviews: 10,
    price: "30,000",
    people: 10,
    instant: false,
  },
  {
    images: ["/listing-4.jpeg", "/listing-2.jpeg", "/listing-1.jpeg", "/listing-1.jpeg"],
    name: "All Exclusive Shanty studios",
    location: "Ikeja, Lagos",
    ratings: "4.5",
    reviews: 10,
    price: "30,000",
    people: 10,
    instant: true,
  },
  {
    images: ["/listing-1.jpeg", "/listing-2.jpeg", "/listing-3.jpeg", "/listing-4.jpeg"],
    name: "All Exclusive Shanty studios",
    location: "Ikeja, Lagos",
    ratings: "5.0",
    reviews: 10,
    price: "30,000",
    people: 10,
    instant: true,
  },
  {
    images: ["/listing-2.jpeg", "/listing-1.jpeg", "/listing-3.jpeg", "/listing-4.jpeg"],
    name: "All Exclusive Shanty studios",
    location: "Ikeja, Lagos",
    ratings: "4.9",
    reviews: 10,
    price: "30,000",
    people: 10,
    instant: false,
  },
  {
    images: ["/listing-3.jpeg", "/listing-2.jpeg", "/listing-1.jpeg", "/listing-4.jpeg"],
    name: "All Exclusive Shanty studios",
    location: "Ikeja, Lagos",
    ratings: "4.6",
    reviews: 10,
    price: "30,000",
    people: 10,
    instant: false,
  },
  {
    images: ["/listing-4.jpeg", "/listing-2.jpeg", "/listing-1.jpeg", "/listing-1.jpeg"],
    name: "All Exclusive Shanty studios",
    location: "Ikeja, Lagos",
    ratings: "4.5",
    reviews: 10,
    price: "30,000",
    people: 10,
    instant: true,
  },
  {
    images: ["/listing-1.jpeg", "/listing-2.jpeg", "/listing-3.jpeg", "/listing-4.jpeg"],
    name: "All Exclusive Shanty studios",
    location: "Ikeja, Lagos",
    ratings: "5.0",
    reviews: 10,
    price: "30,000",
    people: 10,
    instant: true,
  },
  {
    images: ["/listing-2.jpeg", "/listing-1.jpeg", "/listing-3.jpeg", "/listing-4.jpeg"],
    name: "All Exclusive Shanty studios",
    location: "Ikeja, Lagos",
    ratings: "4.9",
    reviews: 10,
    price: "30,000",
    people: 10,
    instant: false,
  },
  {
    images: ["/listing-3.jpeg", "/listing-2.jpeg", "/listing-1.jpeg", "/listing-4.jpeg"],
    name: "All Exclusive Shanty studios",
    location: "Ikeja, Lagos",
    ratings: "4.6",
    reviews: 10,
    price: "30,000",
    people: 10,
    instant: false,
  },
  {
    images: ["/listing-4.jpeg", "/listing-2.jpeg", "/listing-1.jpeg", "/listing-1.jpeg"],
    name: "All Exclusive Shanty studios",
    location: "Ikeja, Lagos",
    ratings: "4.5",
    reviews: 10,
    price: "30,000",
    people: 10,
    instant: true,
  },
  {
    images: ["/listing-1.jpeg", "/listing-2.jpeg", "/listing-3.jpeg", "/listing-4.jpeg"],
    name: "All Exclusive Shanty studios",
    location: "Ikeja, Lagos",
    ratings: "5.0",
    reviews: 10,
    price: "30,000",
    people: 10,
    instant: true,
  },
  {
    images: ["/listing-2.jpeg", "/listing-1.jpeg", "/listing-3.jpeg", "/listing-4.jpeg"],
    name: "All Exclusive Shanty studios",
    location: "Ikeja, Lagos",
    ratings: "4.9",
    reviews: 10,
    price: "30,000",
    people: 10,
    instant: false,
  },
  {
    images: ["/listing-3.jpeg", "/listing-2.jpeg", "/listing-1.jpeg", "/listing-4.jpeg"],
    name: "All Exclusive Shanty studios",
    location: "Ikeja, Lagos",
    ratings: "4.6",
    reviews: 10,
    price: "30,000",
    people: 10,
    instant: false,
  },
  {
    images: ["/listing-4.jpeg", "/listing-2.jpeg", "/listing-1.jpeg", "/listing-1.jpeg"],
    name: "All Exclusive Shanty studios",
    location: "Ikeja, Lagos",
    ratings: "4.5",
    reviews: 10,
    price: "30,000",
    people: 10,
    instant: true,
  },
  {
    images: ["/listing-1.jpeg", "/listing-2.jpeg", "/listing-3.jpeg", "/listing-4.jpeg"],
    name: "All Exclusive Shanty studios",
    location: "Ikeja, Lagos",
    ratings: "5.0",
    reviews: 10,
    price: "30,000",
    people: 10,
    instant: true,
  },
  {
    images: ["/listing-2.jpeg", "/listing-1.jpeg", "/listing-3.jpeg", "/listing-4.jpeg"],
    name: "All Exclusive Shanty studios",
    location: "Ikeja, Lagos",
    ratings: "4.9",
    reviews: 10,
    price: "30,000",
    people: 10,
    instant: false,
  },
  {
    images: ["/listing-3.jpeg", "/listing-2.jpeg", "/listing-1.jpeg", "/listing-4.jpeg"],
    name: "All Exclusive Shanty studios",
    location: "Ikeja, Lagos",
    ratings: "4.6",
    reviews: 10,
    price: "30,000",
    people: 10,
    instant: false,
  },
  {
    images: ["/listing-4.jpeg", "/listing-2.jpeg", "/listing-1.jpeg", "/listing-1.jpeg"],
    name: "All Exclusive Shanty studios",
    location: "Ikeja, Lagos",
    ratings: "4.5",
    reviews: 10,
    price: "30,000",
    people: 10,
    instant: true,
  },
  {
    images: ["/listing-1.jpeg", "/listing-2.jpeg", "/listing-3.jpeg", "/listing-4.jpeg"],
    name: "All Exclusive Shanty studios",
    location: "Ikeja, Lagos",
    ratings: "5.0",
    reviews: 10,
    price: "30,000",
    people: 10,
    instant: true,
  },
  {
    images: ["/listing-2.jpeg", "/listing-1.jpeg", "/listing-3.jpeg", "/listing-4.jpeg"],
    name: "All Exclusive Shanty studios",
    location: "Ikeja, Lagos",
    ratings: "4.9",
    reviews: 10,
    price: "30,000",
    people: 10,
    instant: false,
  },
  {
    images: ["/listing-3.jpeg", "/listing-2.jpeg", "/listing-1.jpeg", "/listing-4.jpeg"],
    name: "All Exclusive Shanty studios",
    location: "Ikeja, Lagos",
    ratings: "4.6",
    reviews: 10,
    price: "30,000",
    people: 10,
    instant: false,
  },
  {
    images: ["/listing-4.jpeg", "/listing-2.jpeg", "/listing-1.jpeg", "/listing-1.jpeg"],
    name: "All Exclusive Shanty studios",
    location: "Ikeja, Lagos",
    ratings: "4.5",
    reviews: 10,
    price: "30,000",
    people: 10,
    instant: true,
  },
];

export const profileListings = [
  {
    image: "/listing-2.jpeg",
    name: "All Exclusive Shanty studios",
    description:
      "Morem ipsum dolor sit amet, consectetur adipiscing elit. Nunc vulputate libero et velit interdum, ac aliquet odio mattis.",
    location: "Ikeja, Lagos",
    ratings: "5.0",
    reviews: 10,
    price: "30,000",
    people: 10,
  },
  {
    image: "/listing-2.jpeg",
    name: "All Exclusive Shanty studios",
    description:
      "Morem ipsum dolor sit amet, consectetur adipiscing elit. Nunc vulputate libero et velit interdum, ac aliquet odio mattis.",
    location: "Ikeja, Lagos",
    ratings: "5.0",
    reviews: 10,
    price: "30,000",
    people: 10,
  },
  {
    image: "/listing-2.jpeg",
    name: "All Exclusive Shanty studios",
    description:
      "Morem ipsum dolor sit amet, consectetur adipiscing elit. Nunc vulputate libero et velit interdum, ac aliquet odio mattis.",
    location: "Ikeja, Lagos",
    ratings: "5.0",
    reviews: 10,
    price: "30,000",
    people: 10,
  },
  {
    image: "/listing-2.jpeg",
    name: "All Exclusive Shanty studios",
    description:
      "Morem ipsum dolor sit amet, consectetur adipiscing elit. Nunc vulputate libero et velit interdum, ac aliquet odio mattis.",
    location: "Ikeja, Lagos",
    ratings: "5.0",
    reviews: 10,
    price: "30,000",
    people: 10,
  },
  {
    image: "/listing-2.jpeg",
    name: "All Exclusive Shanty studios",
    description:
      "Morem ipsum dolor sit amet, consectetur adipiscing elit. Nunc vulputate libero et velit interdum, ac aliquet odio mattis.",
    location: "Ikeja, Lagos",
    ratings: "5.0",
    reviews: 10,
    price: "30,000",
    people: 10,
  },
  {
    image: "/listing-2.jpeg",
    name: "All Exclusive Shanty studios",
    description:
      "Morem ipsum dolor sit amet, consectetur adipiscing elit. Nunc vulputate libero et velit interdum, ac aliquet odio mattis.",
    location: "Ikeja, Lagos",
    ratings: "5.0",
    reviews: 10,
    price: "30,000",
    people: 10,
  },
  {
    image: "/listing-2.jpeg",
    name: "All Exclusive Shanty studios",
    description:
      "Morem ipsum dolor sit amet, consectetur adipiscing elit. Nunc vulputate libero et velit interdum, ac aliquet odio mattis.",
    location: "Ikeja, Lagos",
    ratings: "5.0",
    reviews: 10,
    price: "30,000",
    people: 10,
  },
  {
    image: "/listing-2.jpeg",
    name: "All Exclusive Shanty studios",
    description:
      "Morem ipsum dolor sit amet, consectetur adipiscing elit. Nunc vulputate libero et velit interdum, ac aliquet odio mattis.",
    location: "Ikeja, Lagos",
    ratings: "5.0",
    reviews: 10,
    price: "30,000",
    people: 10,
  },
  {
    image: "/listing-2.jpeg",
    name: "All Exclusive Shanty studios",
    description:
      "Morem ipsum dolor sit amet, consectetur adipiscing elit. Nunc vulputate libero et velit interdum, ac aliquet odio mattis.",
    location: "Ikeja, Lagos",
    ratings: "5.0",
    reviews: 10,
    price: "30,000",
    people: 10,
  },
];
